// shared/messaging.ts
// Centralized message type constants used between UI and background SW

export const EXECUTE_WORKFLOW = "EXECUTE_WORKFLOW";
export const WORKFLOW_COMPLETE = "WORKFLOW_COMPLETE";
export const WORKFLOW_FAILED = "WORKFLOW_FAILED";
export const WORKFLOW_STEP_UPDATE = "WORKFLOW_STEP_UPDATE";
export const TURN_FINALIZED = "TURN_FINALIZED";
export const TURN_CREATED = "TURN_CREATED";

export const GET_FULL_HISTORY = "GET_FULL_HISTORY";
export const GET_HISTORY_SESSION = "GET_HISTORY_SESSION";
export const GET_LAST_ESCALATION = "GET_LAST_ESCALATION";
export const GET_SYSTEM_STATUS = "GET_SYSTEM_STATUS";

// Maintenance / cleanup
export const DELETE_SESSION = "DELETE_SESSION";
export const DELETE_SESSIONS = "DELETE_SESSIONS";
// Rename existing session title
export const RENAME_SESSION = "RENAME_SESSION";

// ChatGPT Provider Messages
export const CHATGPT_CHECK_REQUIREMENTS = "CHATGPT_CHECK_REQUIREMENTS";
export const CHATGPT_TEST_ARKOSE = "CHATGPT_TEST_ARKOSE";
export const CHATGPT_GET_STATUS = "CHATGPT_GET_STATUS";
export const CHATGPT_GENERATE_PROOF = "CHATGPT_GENERATE_PROOF";
export const CHATGPT_RETRIEVE_ARKOSE = "CHATGPT_RETRIEVE_ARKOSE";
export const REFINE_PROMPT = "REFINE_PROMPT";
export const REFRESH_AUTH_STATUS = "REFRESH_AUTH_STATUS";
